### ISSUE TITLE
Allow overriding pdfjs.GlobalWorkerOptions.workerSrc

### ISSUE THREAD

**Issue by Janhouse** [cyntler/react-doc-viewer#180]
Could we somehow pass the value of pdfjs.GlobalWorkerOptions.workerSrc to the component? It is currently hardcoded to a CDN and I do not want to make outside requests.

**Comment by vnt-83** [comment]
https://github.com/cyntler/react-doc-viewer/issues/157

**Comment by vnt-83** [comment]
I found workaround:

**1)** In file `node_modules/@cyntler/react-doc-viewer/dist/cjs/renderers/pdf/index.js` comment line17:

```react_pdf_1.pdfjs.GlobalWorkerOptions.workerSrc = "https://unpkg.com/pdfjs-dist@".concat(react_pdf_1.pdfjs.version, "/legacy/build/pdf.worker.min.js");```

**2)** In file `node_modules/@cyntler/react-doc-viewer/dist/esm/renderers/pdf/index.js` comment line 12:

```pdfjs.GlobalWorkerOptions.workerSrc = "https://unpkg.com/pdfjs-dist@".concat(pdfjs.version, "/legacy/build/pdf.worker.min.js");```

and add after (instead of) it this line:

```pdfjs.GlobalWorkerOptions.workerSrc = "/js/pdf.worker.min.js";```

**3)** Put `pdf.worker.min.js` to `js` folder in you `public` folder. 
`pdf.worker.min.js` take from CDN or from `node_modules/pdfjs-dist/legacy/build/` folder.

**Comment by Janhouse** [comment]
That is not a workaround. That requires making changes to the module itself.

**Comment by vnt-83** [comment]
Yes, but it works. There is always a choice: allow external requests or do something. When external requests are not allowed, then there is no choice.

**Comment by Janhouse** [comment]
How about adding an option to this library?

**Comment by vnt-83** [comment]
I would love to, but unfortunately there is no such opportunity.

**Comment by cyntler** [comment]
@Janhouse `workerSrc`  has been fixed yesterday at the newest version,
