### ISSUE TITLE
An error occurred We're sorry, but for some reason we can't open this for you.

### ISSUE THREAD

**Issue by kamelabiad** [cyntler/react-doc-viewer#259]
we are getting this error message when trying to view a docx file,

An error occurred
We're sorry, but for some reason we can't open this for you.
I have even tried to render it by making it public published through URL , but same issue

the file is attached . 
[file-sample_1MB.docx](https://github.com/cyntler/react-doc-viewer/files/15436181/file-sample_1MB.docx)

**Comment by kamelabiad** [comment]
And this is the code that we are using to render the file locally
![image](https://github.com/cyntler/react-doc-viewer/assets/9218860/27199ddb-4f91-45ce-8496-f3db77fc61db)

**Comment by kamelabiad** [comment]
@cyntler you support on this ticket is highly appreciated

**Comment by cyntler** [comment]
@kamelabiad Hey! Read the readme please: **This library uses the official MS Office online document viewing service. This means it works on an iframe basis and only supports public file URLs! Therefore, it may not be compatible with all projects. Currently, there is no way to natively render MS Office documents in the browser.**

In your case, you `require()` the file. It means the file is available on your site only and the require() function returns filename with extension, not public URL to this file. You have to provide full public URL with protocol to the library as `uri` to display DOCX.

There are a lot of issues regarding to MS Office files rendering. I think that the best way to resolve this problem is remove this functionality. ;)

It is very very problematic.
